
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyekausvwqajztspkjcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55ZWthdXN2d3Fhanp0c3BramNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzQyOTIsImV4cCI6MjA1ODQxMDI5Mn0.2iVSM8ptJEURkryL_FB0dvF_WQNQTzezENBYlYOtvqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
